services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdam_app
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - sqlite_data:/var/www/html/database
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://139.162.5.182:8088
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - IPAYMU_API_KEY=5F446413-B4AB-4F1D-9423-BB4E70E67D01
      - IPAYMU_VA=1179002284733404
      - IPAYMU_URL=https://my.ipaymu.com/api/v2
    restart: unless-stopped

volumes:
  sqlite_data:
